package com.example.enums;

public enum Sits {
    ZERO_ZERO, ZERO_ONE, ZERO_TWO, ZERO_THREE, ZERO_FOUR, ZERO_FIVE, ZERO_SIX,
    ONE_ZERO, ONE_ONE, ONE_TWO, ONE_THREE, ONE_FOUR, ONE_FIVE, ONE_SIX,
    TWO_ZERO, TWO_ONE, TWO_TWO, TWO_THREE, TWO_FOUR, TWO_FIVE, TWO_SIX,
    THREE_ZERO, THREE_ONE, THREE_TWO, THREE_THREE, THREE_FOUR, THREE_FIVE, THREE_SIX,
    FOUR_ZERO, FOUR_ONE, FOUR_TWO, FOUR_THREE, FOUR_FOUR, FOUR_FIVE, FOUR_SIX,
    FIVE_ZERO, FIVE_ONE, FIVE_TWO, FIVE_THREE, FIVE_FOUR, FIVE_FIVE, FIVE_SIX,
    SIX_ZERO, SIX_ONE, SIX_TWO, SIX_THREE, SIX_FOUR, SIX_FIVE, SIX_SIX,
    SEVEN_ZERO, SEVEN_ONE, SEVEN_TWO, SEVEN_THREE, SEVEN_FOUR, SEVEN_FIVE, SEVEN_SIX,
    EIGHT_ZERO, EIGHT_ONE, EIGHT_TWO, EIGHT_THREE, EIGHT_FOUR, EIGHT_FIVE, EIGHT_SIX,
    NINE_ZERO, NINE_ONE, NINE_TWO, NINE_THREE, NINE_FOUR, NINE_FIVE, NINE_SIX,
    TEN_ZERO, TEN_ONE, TEN_TWO, TEN_THREE, TEN_FOUR, TEN_FIVE, TEN_SIX
    
}
